title = "GhoulDen"
theme = "duckquill"
base_url = "https://ghoulboii.github.io/"

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
primary_color = "#fa69ff"
primary_color_alpha = "rgba(250, 105, 255, 0.2)"
stylesheets = ["main.css"]
issues_url = "https://github.com/GhoulBoii/GhoulBoii.github.io/issues"
source_url = "https://github.com/GhoulBoii/GhoulBoii.github.io"
date_format = "%d %B %Y"

[extra.nav]
# Display Atom/RSS feed button in the nav
show_feed = true
# Links used in the nav
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/projects/index.md", name = "Projects" },
  { url = "@/about/index.md", name = "About" },
]

[extra.comments]
host = ""
user = ""
